import type { SfpDataset } from '@/lib/site-feasibility-platform/types';

export const siteFeasibilityMock: SfpDataset = {
  study: {
    code: 'RESP-204',
    title: 'Interstitial Lung Disease Precision Site Feasibility Program',
    phase: 'Phase II',
    indication: 'ILD',
    targetEnrollment: 180,
    sponsor: 'Respira Therapeutics',
    protocolVersion: 'v3.2',
    complexity: {
      overall: 78,
      inclusionExclusion: 82,
      procedures: 74,
      operational: 79,
      burdenLabel: 'High'
    },
    countries: ['Germany', 'Spain', 'Poland', 'United Kingdom', 'Italy', 'Czech Republic']
  },
  countries: [
    { name: 'Germany', startupDays: 112, startupRisk: 63, patientAccess: 85, competitionRisk: 58, diversityFit: 62, forecastEnrollment: 34, regulatoryReadiness: 86 },
    { name: 'Spain', startupDays: 87, startupRisk: 41, patientAccess: 74, competitionRisk: 36, diversityFit: 81, forecastEnrollment: 28, regulatoryReadiness: 79 },
    { name: 'Poland', startupDays: 76, startupRisk: 32, patientAccess: 68, competitionRisk: 27, diversityFit: 56, forecastEnrollment: 24, regulatoryReadiness: 76 },
    { name: 'United Kingdom', startupDays: 98, startupRisk: 49, patientAccess: 83, competitionRisk: 66, diversityFit: 73, forecastEnrollment: 31, regulatoryReadiness: 88 },
    { name: 'Italy', startupDays: 91, startupRisk: 44, patientAccess: 77, competitionRisk: 42, diversityFit: 71, forecastEnrollment: 30, regulatoryReadiness: 74 },
    { name: 'Czech Republic', startupDays: 71, startupRisk: 29, patientAccess: 61, competitionRisk: 24, diversityFit: 52, forecastEnrollment: 19, regulatoryReadiness: 72 }
  ],
  sites: [
    {
      id: 'DE-BER-01',
      name: 'Charite Pulmonary Trial Center',
      country: 'Germany',
      city: 'Berlin',
      principalInvestigator: 'Dr. Eva Schubert',
      startupDays: 118,
      startupRisk: 67,
      patientMatchScore: 92,
      patientPool: 94,
      diversityFit: 58,
      competitionRisk: 64,
      dataQualityScore: 90,
      enrollmentRate: 3.8,
      protocolFit: 89,
      preferredPopulation: 'Fibrotic ILD referral network',
      rationale: ['Highest phenotype match', 'Strong imaging-readiness', 'Competing ILD program may slow activation'],
      tags: ['high-match', 'slow-startup']
    },
    {
      id: 'DE-MUN-02',
      name: 'Munich Lung Institute',
      country: 'Germany',
      city: 'Munich',
      principalInvestigator: 'Prof. Lena Kurz',
      startupDays: 101,
      startupRisk: 53,
      patientMatchScore: 84,
      patientPool: 80,
      diversityFit: 60,
      competitionRisk: 61,
      dataQualityScore: 88,
      enrollmentRate: 3.2,
      protocolFit: 86,
      preferredPopulation: 'Academic ILD center',
      rationale: ['Reliable data quality', 'Competitive trial overlap is elevated', 'Moderate start-up friction'],
      tags: ['competition-risk']
    },
    {
      id: 'ES-MAD-03',
      name: 'Madrid Respiratory Research Unit',
      country: 'Spain',
      city: 'Madrid',
      principalInvestigator: 'Dr. Carla Nuñez',
      startupDays: 83,
      startupRisk: 39,
      patientMatchScore: 81,
      patientPool: 76,
      diversityFit: 87,
      competitionRisk: 31,
      dataQualityScore: 82,
      enrollmentRate: 3.4,
      protocolFit: 83,
      preferredPopulation: 'Urban referral + community mix',
      rationale: ['Strong diversity fit', 'Balanced startup and enrollment', 'Good regional referral density'],
      tags: ['diversity-fit']
    },
    {
      id: 'ES-BAR-04',
      name: 'Barcelona Thoracic Collaborative',
      country: 'Spain',
      city: 'Barcelona',
      principalInvestigator: 'Dr. Oriol Serra',
      startupDays: 92,
      startupRisk: 45,
      patientMatchScore: 78,
      patientPool: 82,
      diversityFit: 84,
      competitionRisk: 38,
      dataQualityScore: 80,
      enrollmentRate: 3.0,
      protocolFit: 79,
      preferredPopulation: 'ILD and autoimmune overlap',
      rationale: ['Consistent referral stream', 'Diversity contribution is above target', 'Startup speed is acceptable'],
      tags: ['balanced']
    },
    {
      id: 'PL-WAR-05',
      name: 'Warsaw Respiratory Network',
      country: 'Poland',
      city: 'Warsaw',
      principalInvestigator: 'Dr. Marta Zielinska',
      startupDays: 72,
      startupRisk: 28,
      patientMatchScore: 69,
      patientPool: 63,
      diversityFit: 49,
      competitionRisk: 25,
      dataQualityScore: 77,
      enrollmentRate: 2.4,
      protocolFit: 74,
      preferredPopulation: 'Community pulmonary referrals',
      rationale: ['Fast startup path', 'Lower patient density than top-tier sites', 'Useful acceleration node'],
      tags: ['fast-startup', 'lower-pool']
    },
    {
      id: 'PL-KRA-06',
      name: 'Krakow Fibrosis Site',
      country: 'Poland',
      city: 'Krakow',
      principalInvestigator: 'Dr. Pawel Kaczmarek',
      startupDays: 78,
      startupRisk: 33,
      patientMatchScore: 74,
      patientPool: 67,
      diversityFit: 51,
      competitionRisk: 29,
      dataQualityScore: 75,
      enrollmentRate: 2.7,
      protocolFit: 76,
      preferredPopulation: 'Interstitial fibrosis registry',
      rationale: ['Operationally efficient', 'Limited diversity contribution', 'Stable investigator engagement'],
      tags: ['fast-startup']
    },
    {
      id: 'UK-LON-07',
      name: 'London ILD Translational Centre',
      country: 'United Kingdom',
      city: 'London',
      principalInvestigator: 'Prof. James Ellery',
      startupDays: 106,
      startupRisk: 56,
      patientMatchScore: 90,
      patientPool: 89,
      diversityFit: 82,
      competitionRisk: 72,
      dataQualityScore: 93,
      enrollmentRate: 3.9,
      protocolFit: 91,
      preferredPopulation: 'Rare phenotype concentration',
      rationale: ['Excellent all-around fit', 'Highest competition exposure', 'Leadership showcase site if activated'],
      tags: ['high-match', 'competition-risk', 'diversity-fit']
    },
    {
      id: 'UK-MAN-08',
      name: 'Manchester Airway Trials Hub',
      country: 'United Kingdom',
      city: 'Manchester',
      principalInvestigator: 'Dr. Amelia Frost',
      startupDays: 94,
      startupRisk: 46,
      patientMatchScore: 79,
      patientPool: 75,
      diversityFit: 76,
      competitionRisk: 48,
      dataQualityScore: 84,
      enrollmentRate: 3.1,
      protocolFit: 82,
      preferredPopulation: 'Regional ILD network',
      rationale: ['Good operational center', 'Competition moderate', 'Balanced candidate for shortlist'],
      tags: ['balanced']
    },
    {
      id: 'IT-MIL-09',
      name: 'Milan PulmoScience Center',
      country: 'Italy',
      city: 'Milan',
      principalInvestigator: 'Dr. Sofia Bianchi',
      startupDays: 88,
      startupRisk: 42,
      patientMatchScore: 86,
      patientPool: 78,
      diversityFit: 73,
      competitionRisk: 39,
      dataQualityScore: 85,
      enrollmentRate: 3.3,
      protocolFit: 88,
      preferredPopulation: 'Advanced ILD + imaging infrastructure',
      rationale: ['High protocol fit', 'Good startup rhythm', 'Solid country anchor candidate'],
      tags: ['recommended']
    },
    {
      id: 'IT-ROM-10',
      name: 'Rome Clinical Pulmonary Institute',
      country: 'Italy',
      city: 'Rome',
      principalInvestigator: 'Prof. Giulia Ferri',
      startupDays: 95,
      startupRisk: 47,
      patientMatchScore: 72,
      patientPool: 74,
      diversityFit: 69,
      competitionRisk: 46,
      dataQualityScore: 79,
      enrollmentRate: 2.8,
      protocolFit: 77,
      preferredPopulation: 'Referral-led respiratory clinic',
      rationale: ['Good backup site', 'Protocol complexity may slow screening', 'Moderate patient pool'],
      tags: ['backup']
    },
    {
      id: 'CZ-PRA-11',
      name: 'Prague Respiratory Excellence Unit',
      country: 'Czech Republic',
      city: 'Prague',
      principalInvestigator: 'Dr. Tomas Novotny',
      startupDays: 69,
      startupRisk: 27,
      patientMatchScore: 66,
      patientPool: 58,
      diversityFit: 46,
      competitionRisk: 22,
      dataQualityScore: 76,
      enrollmentRate: 2.2,
      protocolFit: 72,
      preferredPopulation: 'Efficient operational deployment',
      rationale: ['Fastest activation path', 'Patient pool is thin', 'Useful in speed-first scenario'],
      tags: ['fast-startup', 'patient-pool-low']
    },
    {
      id: 'CZ-BRN-12',
      name: 'Brno Lung Analytics Site',
      country: 'Czech Republic',
      city: 'Brno',
      principalInvestigator: 'Dr. Petra Havel',
      startupDays: 74,
      startupRisk: 31,
      patientMatchScore: 64,
      patientPool: 55,
      diversityFit: 44,
      competitionRisk: 21,
      dataQualityScore: 73,
      enrollmentRate: 2.0,
      protocolFit: 70,
      preferredPopulation: 'Secondary acceleration node',
      rationale: ['Quick startup', 'Lower complexity adoption risk', 'Recruitment upside limited'],
      tags: ['fast-startup']
    },
    {
      id: 'DE-HAM-13',
      name: 'Hamburg Interstitial Care Site',
      country: 'Germany',
      city: 'Hamburg',
      principalInvestigator: 'Dr. Nora Feld',
      startupDays: 116,
      startupRisk: 62,
      patientMatchScore: 88,
      patientPool: 86,
      diversityFit: 57,
      competitionRisk: 55,
      dataQualityScore: 87,
      enrollmentRate: 3.5,
      protocolFit: 84,
      preferredPopulation: 'Severe ILD referral pool',
      rationale: ['Very strong patient access', 'Activation burden is high', 'Potential Tier 1 with focused support'],
      tags: ['high-match', 'slow-startup']
    },
    {
      id: 'ES-SEV-14',
      name: 'Seville Pulmonary Access Site',
      country: 'Spain',
      city: 'Seville',
      principalInvestigator: 'Dr. Lucia Morales',
      startupDays: 81,
      startupRisk: 35,
      patientMatchScore: 76,
      patientPool: 72,
      diversityFit: 83,
      competitionRisk: 28,
      dataQualityScore: 78,
      enrollmentRate: 2.9,
      protocolFit: 80,
      preferredPopulation: 'Broader respiratory access network',
      rationale: ['High diversity contribution', 'Clean startup path', 'Medium recruitment output'],
      tags: ['diversity-fit', 'recommended']
    },
    {
      id: 'PL-GDA-15',
      name: 'Gdansk Rare Lung Registry Site',
      country: 'Poland',
      city: 'Gdansk',
      principalInvestigator: 'Dr. Alicja Wojcik',
      startupDays: 84,
      startupRisk: 37,
      patientMatchScore: 71,
      patientPool: 61,
      diversityFit: 47,
      competitionRisk: 19,
      dataQualityScore: 81,
      enrollmentRate: 2.5,
      protocolFit: 75,
      preferredPopulation: 'Rare ILD sub-segments',
      rationale: ['Registry-enabled targeting', 'Limited total volume', 'Clean competitive landscape'],
      tags: ['specialty-pool']
    },
    {
      id: 'UK-GLA-16',
      name: 'Glasgow Pulmonary Innovation Site',
      country: 'United Kingdom',
      city: 'Glasgow',
      principalInvestigator: 'Dr. Isla Kerr',
      startupDays: 89,
      startupRisk: 43,
      patientMatchScore: 73,
      patientPool: 69,
      diversityFit: 78,
      competitionRisk: 44,
      dataQualityScore: 83,
      enrollmentRate: 2.8,
      protocolFit: 79,
      preferredPopulation: 'Underserved regional cohort',
      rationale: ['Strong diversity signal', 'Moderate overall score', 'Good complement to London'],
      tags: ['diversity-fit']
    },
    {
      id: 'IT-NAP-17',
      name: 'Naples Respiratory Research Network',
      country: 'Italy',
      city: 'Naples',
      principalInvestigator: 'Dr. Matteo Russo',
      startupDays: 93,
      startupRisk: 45,
      patientMatchScore: 68,
      patientPool: 70,
      diversityFit: 72,
      competitionRisk: 34,
      dataQualityScore: 74,
      enrollmentRate: 2.6,
      protocolFit: 73,
      preferredPopulation: 'Regional ILD screening base',
      rationale: ['Adequate pool', 'Not top-tier on quality', 'Scenario-dependent inclusion'],
      tags: ['watch']
    },
    {
      id: 'CZ-OST-18',
      name: 'Ostrava FastStart Pulmonary Site',
      country: 'Czech Republic',
      city: 'Ostrava',
      principalInvestigator: 'Dr. Jan Vesely',
      startupDays: 68,
      startupRisk: 26,
      patientMatchScore: 59,
      patientPool: 52,
      diversityFit: 41,
      competitionRisk: 18,
      dataQualityScore: 71,
      enrollmentRate: 1.9,
      protocolFit: 67,
      preferredPopulation: 'Fast activation reserve site',
      rationale: ['Very fast startup', 'Patient pool is the lowest in network', 'Reserve capacity only'],
      tags: ['fast-startup', 'reserve']
    }
  ],
  scenarios: [
    {
      id: 'balanced',
      label: 'Balanced launch',
      assumptions: {
        startupWeight: 0.26,
        enrollmentWeight: 0.34,
        diversityWeight: 0.18,
        competitionPenalty: 0.22
      },
      expectedLpiWeeks: 39,
      expectedActivatedSites: 9,
      expectedEnrollmentAtMonth6: 71,
      narrative: 'Balances startup friction and patient flow; leadership-friendly default shortlist.'
    },
    {
      id: 'speed-first',
      label: 'Speed-first',
      assumptions: {
        startupWeight: 0.42,
        enrollmentWeight: 0.28,
        diversityWeight: 0.1,
        competitionPenalty: 0.2
      },
      expectedLpiWeeks: 34,
      expectedActivatedSites: 8,
      expectedEnrollmentAtMonth6: 59,
      narrative: 'Prioritizes activation speed to de-risk FPI and early operational optics.'
    },
    {
      id: 'enrollment-first',
      label: 'Enrollment-first',
      assumptions: {
        startupWeight: 0.18,
        enrollmentWeight: 0.46,
        diversityWeight: 0.14,
        competitionPenalty: 0.22
      },
      expectedLpiWeeks: 37,
      expectedActivatedSites: 10,
      expectedEnrollmentAtMonth6: 82,
      narrative: 'Biases toward sites with stronger ILD pool even if startup support must increase.'
    },
    {
      id: 'representation',
      label: 'Representation-led',
      assumptions: {
        startupWeight: 0.18,
        enrollmentWeight: 0.28,
        diversityWeight: 0.34,
        competitionPenalty: 0.2
      },
      expectedLpiWeeks: 40,
      expectedActivatedSites: 9,
      expectedEnrollmentAtMonth6: 68,
      narrative: 'Optimizes diversity fit while preserving enough activation velocity for leadership confidence.'
    }
  ],
  catalog: [
    {
      id: 'ctg-benchmark',
      name: 'ClinicalTrials.gov ILD Benchmark Pack',
      type: 'External Registry',
      freshness: 'Updated 3 days ago',
      granularity: 'Study + country + site proxy',
      coverage: '2018-2025 ILD interventional studies',
      fields: ['country', 'site count', 'phase', 'sponsor', 'status'],
      owner: 'Competitive intelligence',
      usage: 'Country benchmark and competition risk scoring'
    },
    {
      id: 'startup-benchmark',
      name: 'EU Startup Benchmark',
      type: 'Internal Benchmark',
      freshness: 'Updated this week',
      granularity: 'Country + site archetype',
      coverage: 'Phase II respiratory portfolio',
      fields: ['startup days', 'contract cycle', 'EC approval lag'],
      owner: 'Clinical operations excellence',
      usage: 'Startup forecast and risk calibration'
    },
    {
      id: 'diversity-panel',
      name: 'Regional Diversity Feasibility Panel',
      type: 'Feasibility Survey',
      freshness: 'Quarterly snapshot',
      granularity: 'Site + referral network',
      coverage: 'EU6 respiratory investigators',
      fields: ['ethnicity reach', 'language support', 'travel burden'],
      owner: 'Patient strategy office',
      usage: 'Diversity-fit scoring and recommendation narrative'
    },
    {
      id: 'protocol-features',
      name: 'RESP-204 Protocol Feature Decomposition',
      type: 'Protocol Artifact',
      freshness: 'Version v3.2',
      granularity: 'Visit + procedure + I/E rule',
      coverage: 'Current study only',
      fields: ['complexity index', 'screen failure risk', 'visit burden'],
      owner: 'Study design lead',
      usage: 'Protocol complexity and site-fit interpretation'
    }
  ],
  settings: {
    scoringWeights: {
      patientMatch: 32,
      startupSpeed: 22,
      diversityFit: 16,
      competitionPenalty: 14,
      dataQuality: 16
    },
    thresholds: {
      tier1Score: 82,
      maxStartupDays: 105,
      maxCompetitionRisk: 60
    }
  }
};

